spring.application.name=chatbot

#Postgres
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chatbot}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Vish@1234}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Gemini AI (OpenAI Compatible)
spring.ai.openai.api-key=${GEMINI_API_KEY:DEMO_KEY}
spring.ai.openai.chat.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.chat.completions-path=/chat/completions
spring.ai.openai.chat.options.model=gemini-1.5-flash
spring.ai.openai.embedding.options.model=text-embedding-004
spring.ai.openai.chat.options.temperature=0.7


# File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Tesseract OCR path (for images)
tesseract.data.path=${TESSERACT_DATA_PATH:C:/Program Files/Tesseract-OCR/tessdata}
